#!/bin/bash

# Declare possible python 3 command
declare -a pyCmds=("ddddd" "python" "python3" "py" "py3")

for i in "${pyCmds[@]}"
do
    # echo "$i"
    # version=`i --verison 2>&1`
    # res=`${i} --version 2>&1 1>/dev/null`
    res=`${i} --version 2>&1`
    # save `cmd --verison` executed status
    vres=$?
    echo $res |grep '3\.[[:digit:]]' >/dev/null

    # Get the absolute path
    DIRECTORY=$(cd `dirname $0` && pwd)

    # if we can find python 3 command
    if [ $vres -eq 0 -a $? -eq 0 ]; then
        # echo "[+] version is: $res, ${i}"
        ${i} $DIRECTORY/create.py $1

        # after folder create
        if [ $? -eq 0 ]; then
            cd $1/build && cmake .. && make && ./$1
        fi
        break
    fi
done
